apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
  namespace: saas-pos
data:
  Caddyfile: |
    :80 {
        handle /admin/* {
            uri strip_prefix /admin
            root * /srv/admin
            try_files {path} /index.html
            file_server
        }
        handle /tenant/* {
            uri strip_prefix /tenant
            root * /srv/tenant
            try_files {path} /index.html
            file_server
        }
        handle /* {
            root * /srv/landing
            try_files {path} /index.html
            file_server
        }
        encode gzip zstd
    }
